# Generated by Django 2.0.4 on 2018-05-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='articleComment',
        ),
        migrations.AddField(
            model_name='comment',
            name='articleComment',
            field=models.ManyToManyField(null=True, to='blog.Article'),
        ),
    ]
