# Generated by Django 2.0.4 on 2018-05-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180519_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='articleComment',
            field=models.ManyToManyField(to='blog.Article'),
        ),
    ]
